// src/pages/Packages/packages.js

const packages = [
  {
    id: 1,
    title: "Ooty Family Escape",
    destination: "Ooty",
    category: "Family",
    price: 8999,
    days: 3,
    nights: 2,
    rating: 4.8,
    imageFolder: "ooty",
    places: ["Botanical Garden", "Ooty Lake", "Doddabetta Peak"],
  },
  {
    id: 2,
    title: "Ooty Premium Retreat",
    destination: "Ooty",
    category: "Couple",
    price: 12999,
    days: 4,
    nights: 3,
    rating: 4.9,
    imageFolder: "ooty",
    places: ["Tea Estates", "Avalanche Lake", "Emerald Lake"],
  },
  {
    id: 3,
    title: "Kodaikanal Lake Retreat",
    destination: "Kodaikanal",
    category: "Couple",
    price: 10999,
    days: 3,
    nights: 2,
    rating: 4.7,
    imageFolder: "kodaikanal",
    places: ["Kodai Lake", "Coaker's Walk", "Pillar Rocks"],
  },
  {
    id: 4,
    title: "Kodaikanal Adventure Trail",
    destination: "Kodaikanal",
    category: "Friends",
    price: 9499,
    days: 3,
    nights: 2,
    rating: 4.6,
    imageFolder: "kodaikanal",
    places: ["Pine Forest", "Guna Cave", "Dolphin Nose"],
  },
  {
    id: 5,
    title: "Madurai Heritage Tour",
    destination: "Madurai",
    category: "Temple",
    price: 7999,
    days: 2,
    nights: 1,
    rating: 4.8,
    imageFolder: "madurai",
    places: ["Meenakshi Temple", "Nayakkar Palace", "Gandhi Museum"],
  },
  {
    id: 6,
    title: "Madurai Cultural Experience",
    destination: "Madurai",
    category: "Solo",
    price: 8499,
    days: 3,
    nights: 2,
    rating: 4.5,
    imageFolder: "madurai",
    places: ["Temple Streets", "Food Trail", "Museum"],
  },
  {
    id: 7,
    title: "Chennai City Explorer",
    destination: "Chennai",
    category: "Friends",
    price: 7499,
    days: 2,
    nights: 1,
    rating: 4.5,
    imageFolder: "chennai",
    places: ["Marina Beach", "Mahabalipuram", "Kapaleeshwarar Temple"],
  },
  {
    id: 8,
    title: "Chennai Heritage Trail",
    destination: "Chennai",
    category: "Solo",
    price: 6999,
    days: 2,
    nights: 1,
    rating: 4.6,
    imageFolder: "chennai",
    places: ["Fort St George", "Museum", "Marina Beach"],
  },
  {
    id: 9,
    title: "Valparai Tea Estate Retreat",
    destination: "Valparai",
    category: "Friends",
    price: 11999,
    days: 3,
    nights: 2,
    rating: 4.8,
    imageFolder: "valparai",
    places: ["Tea Estates", "Sholayar Dam", "Nallamudi Viewpoint"],
  },
  {
    id: 10,
    title: "Valparai Nature Escape",
    destination: "Valparai",
    category: "Couple",
    price: 9999,
    days: 3,
    nights: 2,
    rating: 4.7,
    imageFolder: "valparai",
    places: ["Monkey Falls", "Tea Estate", "Mountain Viewpoint"],
  },
  {
    id: 11,
    title: "Rameswaram Temple Journey",
    destination: "Rameswaram",
    category: "Temple",
    price: 11999,
    days: 3,
    nights: 2,
    rating: 4.8,
    imageFolder: "rameswaram",
    places: ["Ramanathaswamy Temple", "Dhanushkodi", "Pamban Bridge"],
  },
  {
    id: 12,
    title: "Kanyakumari Sunset Escape",
    destination: "Kanyakumari",
    category: "Romantic",
    price: 10999,
    days: 2,
    nights: 1,
    rating: 4.7,
    imageFolder: "kanyakumari",
    places: ["Vivekananda Rock", "Sunset Point", "Kanyakumari Beach"],
  },
  {
    id: 13,
    title: "Yercaud Hill Retreat",
    destination: "Yercaud",
    category: "Couple",
    price: 9999,
    days: 3,
    nights: 2,
    rating: 4.6,
    imageFolder: "yercaud",
    places: ["Yercaud Lake", "Lady's Seat", "Bear's Cave"],
  },
  {
    id: 14,
    title: "Coimbatore Coffee Country",
    destination: "Coimbatore",
    category: "Family",
    price: 10999,
    days: 3,
    nights: 2,
    rating: 4.7,
    imageFolder: "coimbatore",
    places: ["Coffee Estates", "Marudhamalai", "Brookefields"],
  },
  {
    id: 15,
    title: "Chettinad Heritage Trail",
    destination: "Chettinad",
    category: "Culture",
    price: 9999,
    days: 2,
    nights: 1,
    rating: 4.8,
    imageFolder: "chettinad",
    places: ["Heritage Mansions", "Ariyaman Beach", "Local Cuisine"],
  },
];

export const categories = [
  "All",
  "Family",
  "Friends",
  "Solo",
  "Couple",
  "Temple",
];

export const budgetFilters = [
  "All",
  "Under 8000",
  "8000-12000",
  "Above 12000",
];

export const durationFilters = [
  "All",
  "1-2 Days",
  "3-4 Days",
  "5+ Days",
];

export default packages;